### ISSUE TITLE
IllegalArgumentException layout:decorate/data-layout-decorate must appear in the root element of your template

### ISSUE THREAD

**Issue by zhanhb** [ultraq/thymeleaf-layout-dialect#127]
It's available with 1.4.0

```
%TEMPLATE_MODE HTML5

%INPUT
<html th:replace="page1">
    <head></head>
    <body></body>
</html>

%INPUT[page1]
<html layout:decorator="Layout">
    ......
</html>

%INPUT[Layout]
<html>
    ...
</html>

%OUTPUT
<html>
    ...
</html>
```

**Comment by ultraq** [comment]
This one might be hard to fix as is because I  Thymeleaf 3.0 I'm using the `context.elementStack` to tell me what has come before.  I could maybe assume that the `<html>` element is a template root, but the  thus will fail for partial templates like those starting with `<p>` like in the example for partial templates in the docs.

Will need to give this section thought.

**Comment by SnakeSVx** [comment]
I'm getting the same problem when upgrading from thymeleaf 2 to thymeleaf 3.
When I use 
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:th="http://www.thymeleaf.org"
      xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
      lang="nl" class="no-js"
      data-layout-decorator="~{Layout}">
```
everything works, and I get the warning

` The layout:decorator/data-layout-decorator processor has been deprecated and will be removed in the next major version of the layout dialect.  Please use layout:decorate/data-layout-decorate instead to future-proof your code.  See https://github.com/ultraq/thymeleaf-layout-dialect/issues/95 for more information.`

Once I change it to the new one as mentioned in the warning I get this error also.

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:th="http://www.thymeleaf.org"
      xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
      lang="nl" class="no-js"
      data-layout-decorate="~{Layout}">
```

**Comment by ultraq** [comment]
I think I'll just drop this exception because I haven't found a way in Thymeleaf 3 to reliably tell, from a dialect processor point of view, if the element being processed is the root element (leading to things like this happening).  (Thymeleaf 3 did implement an "element stack", but it doesn't seem to be all that reliable for determining a root element.)  I've got a new minor version currently in development, and I'll put the removal of that exception into there in a few days, and hopefully release it after that.

**Comment by ultraq** [comment]
I've just uploaded a `2.2.0-SNAPSHOT` version of the layout dialect that I think does a more accurate check to see if it's in the root element.  Previously it used Thymeleaf 3's "element stack", which caused the problems seen in this issue.  The decorate processor now does a check against the entire current template (which it used to load a bit later in the decoration process, but I've brought it forward so that it can be used here).

**Comment by ddelamotte** [comment]
Hey, i tried to update today to the 2.2.0-RELEASE Layout Dialect version. But since this upgrade (2.1.2 before) i got the IllegalArgumentException layout:decorate/data-layout-decorate must appear in the root element of your template exception without any html changes in my sources

The first lines of my templates are : 
`<html lang="fr" xmlns:th="http://www.thymeleaf.org" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" layout:decorate="~{mobile/decorators/master}">
`
Any ideas?

**Comment by ultraq** [comment]
Darn, so you now get the `IllegalArgumentException` since upgrading to 2.2.0? 😢 

I've got 2 test cases covering this, so maybe you can see if there's something that's in your template that's not here:
 - First one, covers if you very obviously don't put `layout:decorate` in a root element: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Decorate-AppearInRootElementOnly.thtest
 - Second one, covers if you put `layout:decorate` in a root element that comes into the template after another operation, like a `th:replace`: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Decorate-AppearInRootElementReplaced.thtest

Here are the lines of code that try to check for the root element thing: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Source/nz/net/ultraq/thymeleaf/decorators/DecorateProcessor.groovy#L91-L100  What it does is:
 - get the "current template" by reading it from the context
 - find the first opening tag in the template, and make sure it's "equal" to the first event we're processing.  Element equality is defined by code that checks that the attributes are the same and the [element definition](http://www.thymeleaf.org/apidocs/thymeleaf/3.0.3.RELEASE/org/thymeleaf/model/IElementTag.html#getElementDefinition--) are the same.

I can give a few things a try based on what you've written, but what really helps is if you're able to recreate the problem with a really minimal template.  Then I can make test cases out of it and debug what's going on.

**Comment by ddelamotte** [comment]
Hey, after some digging i found out the cause comes from your new test 

> Second one, covers if you put layout:decorate in a root element that comes into the template after another operation, like a th:replace: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Decorate-AppearInRootElementReplaced.thtest

I have a custom dialect (Precedence = 2). As the LayoutDialect precedence is 10, mine is ran before.
The root node (here <html>) has an xmlns:nameofmydialect attribute removed before the layout dialect is reached. Then your test trigger the exception.

**Comment by ultraq** [comment]
Ah, custom dialects.  Never thought of that!  Thanks for looking into it, I'll work on creating an accompanying test and fix.

**Comment by ddelamotte** [comment]
Ok, thx :)

**Comment by ultraq** [comment]
@ddelamotte, I've added a test for interacting with high-priority custom dialects and uploaded a `2.2.1-SNAPSHOT` version of the layout dialect that passes that test.  Would you be able to give that version a try, see if it works for you too?

**Comment by ultraq** [comment]
I'm going to go ahead and publish this fix and version 2.2.1.  If anybody still has trouble with this, feel free to comment on this issue and we can investigate further.

**Comment by xtianus** [comment]
Sorry but with 2.2.1 I still got the following exception:

```

dev 15:57:48 ERROR org.thymeleaf.TemplateEngine - : [THYMELEAF][http-nio-8080-exec-9] Exception processing template "/some/page": An error happened during template parsing (template: "ServletContext resource [/WEB-INF/views/some/page.html]")
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/views/some/page.html]")
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:667)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072)
	at org.thymeleaf.spring4.view.ThymeleafView.renderFragment(ThymeleafView.java:335)
	at org.thymeleaf.spring4.view.ThymeleafView.render(ThymeleafView.java:189)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1282)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:122)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at net.mycompany.security.AuditFilter.doFilterInternal(AuditFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at net.mycompany.security.CheckSessionFilter.doFilter(CheckSessionFilter.java:50)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.attoparser.ParseException: Error during execution of processor 'nz.net.ultraq.thymeleaf.decorators.DecorateProcessor' (template: "/some/layout" - line 4, col 59)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
	... 80 common frames omitted
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'nz.net.ultraq.thymeleaf.decorators.DecorateProcessor' (template: "/some/layout" - line 4, col 59)
	at org.thymeleaf.processor.element.AbstractAttributeModelProcessor.doProcess(AbstractAttributeModelProcessor.java:132)
	at org.thymeleaf.processor.element.AbstractElementModelProcessor.process(AbstractElementModelProcessor.java:98)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper.process(ProcessorConfigurationUtils.java:649)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1510)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.Model.process(Model.java:290)
	at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640)
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.Model.process(Model.java:290)
	at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640)
	at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleCloseElementEnd(TemplateHandlerAdapterMarkupHandler.java:388)
	at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:322)
	at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleCloseElementEnd(OutputExpressionInlinePreProcessorHandler.java:220)
	at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:164)
	at org.attoparser.HtmlElement.handleCloseElementEnd(HtmlElement.java:169)
	at org.attoparser.HtmlMarkupHandler.handleCloseElementEnd(HtmlMarkupHandler.java:412)
	at org.attoparser.MarkupEventProcessorHandler.handleCloseElementEnd(MarkupEventProcessorHandler.java:473)
	at org.attoparser.ParsingElementMarkupUtil.parseCloseElement(ParsingElementMarkupUtil.java:201)
	at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:725)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301)
	... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: layout:decorate/data-layout-decorate must appear in the root element of your template
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at nz.net.ultraq.thymeleaf.decorators.DecorateProcessor.doProcess(DecorateProcessor.groovy:99)
	at org.thymeleaf.processor.element.AbstractAttributeModelProcessor.doProcess(AbstractAttributeModelProcessor.java:76)
	... 108 common frames omitted
```

**Comment by ultraq** [comment]
Heya @xtianus, are you able to provide any hints as to what might be different in your template root elements?  I've currently got 2 special case test cases for this:
 - A root element that gets replaced: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Decorate-AppearInRootElementReplaced.thtest
 - A root element that also defines a custom dialect namespace that has a higher precedence than the layout dialect: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Tests/nz/net/ultraq/thymeleaf/tests/decorators/Interaction-AppearInRootElement.thtest

The previous devs were able to point to things that I had missed (and thus I created the appropriate test cases and fixes above), so any tips might help!  Otherwise, I'll create a 2.2.2-SNAPSHOT version in the next few days with some debug logging around that area which you can turn on and hopefully it gives us more clues as to what's going on.

**Comment by xtianus** [comment]
It work fine for a page that is decorated by the main layout, but it breaks for a page that is decorated by the section layout which is itself decorated by the main layout (three levels in total).

**Comment by xtianus** [comment]
The decorated page, called "folderlist.html", starts with this:

```
<html xmlns:th="http://www.thymeleaf.org" 
	xmlns:yada="http://www.yadaframework.net"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" 
	layout:decorate="~{/gestione/layoutGestione}" 
	th:with="activeSubTab='certificati'">
```

Note the th:with value. The "/gestione/layoutGestione.html" section decorator starts with
```
<html xmlns:th="http://www.thymeleaf.org" 
	xmlns:yada="http://www.yadaframework.net"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" 
	layout:decorate="~{/layouts/mainLayout}" 
	th:with="activeTab='gestione'">
```
Also note the th:with value.
For completeness, the "/layouts/mainLayout.html" global decorator starts with
```
<html xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:th="http://www.thymeleaf.org"
	xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity3"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	xmlns:yada="http://www.yadaframework.net"
  	lang="it">
```

The debugger shows that inside `DecorateProcessor.doProcess()` the exception is thrown because `!contentRootEvent.equalsIgnoreXmlNamespaces(rootElement)` is true.
The toString of contentRootEvent is

```
<html xmlns:th="http://www.thymeleaf.org" 
	xmlns:yada="http://www.yadaframework.net"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" 
	layout:decorate="~{/layouts/mainLayout}" 
	th:with="activeTab='gestione'">
```

The toString of rootElement is:
```
<html xmlns:th="http://www.thymeleaf.org" 
	xmlns:yada="http://www.yadaframework.net"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout" 
	layout:decorate="~{/layouts/mainLayout}" 
	th:with="activeSubTab='certificati',activeTab='gestione'">
```
So even though contentRootEvent and rootElement have the same "templateName" attribute which is "/gestione/layoutGestione", the former only has the th:with of the section decorator (activeTab='gestione'), while the latter also has the th:with of the decorated page (activeSubTab='certificati',activeTab='gestione'). 

Hope this helps.

**Comment by ultraq** [comment]
Hmm, other attribute processors on the element.  That's definitely something to look into.  Thanks!

**Comment by ultraq** [comment]
Hi @xtianus, I've uploaded a `2.2.2-SNAPSHOT` version of the layout dialect with a fix for the issue you've described.  Page decoration utilizes the merge process that merges `th:with` values from 2 different elements together, as you've seen with what happens to your root element in the example you gave .  I've updated the root element check to ignore `th:with` attributes because of this.

Could you please give this snapshot version a try, see if it also fixes things for you?

**Comment by SnakeSVx** [comment]
Seems like this problem also occurs with regular attributes, this time when the html tag contains an attribute `lang="en"`. Using version 2.2.1, have not tested with 2.2.2-SNAPSHOT yet.

Example that fails:
`<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
      data-layout-decorate="~{my_layout}">`
Example that works:
`<html xmlns="http://www.w3.org/1999/xhtml"
      data-layout-decorate="~{my_layout}">`

**Comment by ultraq** [comment]
I tried adding a `lang="en"` to various root elements in the tests I had, and they all seemed to pass for 2.2.2-SNAPSHOT.  I hope you can give that version a try.
