### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jchafik** [ultraq/thymeleaf-layout-dialect#129]
The following results in an ArrayIndexOutOfBoundsException. The modelLevel is incorrectly being decreased to -1.

index.html
```html
<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-4.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
<body layout:replace="default :: layout-body">
  <div layout:fragment="layout-header">New</div>
</body>
</html>
```

default.html
```html
<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml1-strict-thymeleaf-spring4-4.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout">
<body layout:fragment="layout-body">
  <div layout:fragment="layout-header">
    <p>
      <div>test</div>
    </p>
  </div>
</body>
</html>
```

Exception
```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/views/developer.html]")
  ...
Caused by: org.attoparser.ParseException: -1
  at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.MarkupParser.parse(MarkupParser.java:257) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  ... 76 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
  at org.thymeleaf.engine.TemplateModelController.decreaseModelLevel(TemplateModelController.java:333) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.TemplateModelController.shouldProcessCloseElement(TemplateModelController.java:430) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1631) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.Model.process(Model.java:290) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleCloseElementEnd(TemplateHandlerAdapterMarkupHandler.java:388) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:322) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleCloseElementEnd(OutputExpressionInlinePreProcessorHandler.java:220) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleCloseElementEnd(InlinedOutputExpressionMarkupHandler.java:164) ~[thymeleaf-3.0.1.RELEASE.jar:3.0.1.RELEASE]
  at org.attoparser.HtmlElement.handleCloseElementEnd(HtmlElement.java:169) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.HtmlMarkupHandler.handleCloseElementEnd(HtmlMarkupHandler.java:412) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.MarkupEventProcessorHandler.handleCloseElementEnd(MarkupEventProcessorHandler.java:473) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.ParsingElementMarkupUtil.parseCloseElement(ParsingElementMarkupUtil.java:201) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:725) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301) ~[attoparser-2.0.0.RELEASE.jar:2.0.0.RELEASE]
  ... 78 common frames omitted
```

**Comment by ultraq** [comment]
Hi there @jchafik, I've had a look at this bug and what I'm seeing is additional tags inserted by Thymeleaf when processing your example template, notably an empty `IClosingTagElement` after the `<p>` and immediately before the `<div>`.

I think it's because the HTML spec says that a `<p>` end tag can be omitted if it is immediately followed by a `div` (see: https://html.spec.whatwg.org/multipage/semantics.html#the-p-element).  Thymeleaf follows this spec and so inserts a closing tag, thus making your HTML template unbalanced, leading to the exception you're seeing.

So I think the lesson here is to not insert any of the elements mentioned in the "Tag omission in text/html" section of the `<p>` spec right after a `<p>`, and swap it out for something else like a `<span>` instead.

**Comment by jchafik** [comment]
Thanks for the reply!

I can definitely work around that, but wouldn't you think this would still be an issue? From my understanding of the spec, omission of the end tag under these circumstances is technically acceptable, although not necessarily preferable.

The original HTML is balanced, it's the additional (I would think erroneous) insertion that makes it unbalanced. My thought would be that we would only insert the end tag as an attempt to reconcile HTML that was initially unbalanced.

Since `<div>`s are widely used to construct the layout of a site, I can foresee this being a common issue. A quick example may be taken directly from the Bootstrap documentation:
http://getbootstrap.com/css/#forms-controls-static

I would be happy to submit a PR, but it may be a week or two before I can start to dig in. Let me know what you think.

**Comment by ultraq** [comment]
> It's also interesting that this only affects the layout dialect, and that `<p><div>content</div></p>` is accepted by the standard Thymeleaf processor.

Well that's interesting!  The additional closing tag comes from Thymeleaf itself, before the layout dialect processors even get to insert the fragment into the place it's needed.  Maybe I'll give a few more things a try, like the XHTML processing mode and see if different rules apply.

Something else that comes to mind that I do differently from Thymeleaf is that all my processors are "model" processors instead of "tag" ones (a concept introduced in Thymeleaf 3), the biggest difference being that model processors instruct Thymeleaf to parse everything from the open to the closing tag before being run, whereas tag processors only read the open tag and start working there.  I made that decision because I felt model processors more closely represented what I did for Thymeleaf 2.  I suspect Thymeleaf counts this `modelLevel` value after that and then verifies that the model processor hasn't messed with it.  I suspect then that something about the insertion sets it off.

I think I'll give converting some processors to tag ones a try (it is one of my TODO items in #102), see if that helps at all.

Re-opening this issue because it looks like I've still got some research and discussion to go :)

**Comment by jchafik** [comment]
Of course. Where did you upload the snapshot to? I don't see an associated commit or branch here that I can pull down.

**Comment by ultraq** [comment]
Oh, I uploaded one to the Maven snapshots repository, so if you use Maven you can do that, or download the built file from said snapshots repository: https://oss.sonatype.org/content/repositories/snapshots/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/2.0.2-SNAPSHOT/

Otherwise, if you want a build branch I can push that up later today.

**Comment by ultraq** [comment]
I've just pushed the branch `issues/model-level` if you need that to try the change out.

**Comment by jchafik** [comment]
I tested with the 2.0.2-20160905.094158-1 snapshot from the sonatype repository and everything appears to be working correctly. Thank you :)

**Comment by ultraq** [comment]
Awesome! 😃  I'll be releasing 2.0.2 in a few days, hopefully as soon as the dev for the other issue I'm working on gets back and says things are all good there too.
