### ISSUE TITLE
Cannot upgrade to Thymeleaf 3 and LayoutDialect 2

### ISSUE THREAD

**Issue by AlekseiBorsenko** [ultraq/thymeleaf-layout-dialect#156]
Hello! FIrst of all, thank you for this great feature.

For some time I have been waiting for LayoutDialect version, because I wanted to upgrade some of my projects to use Thymeleaf 3.

I'm building with gradle and running a tomcat8 container with gretty.

I have the following dependencies in my build.gradle

```
    // https://mvnrepository.com/artifact/org.thymeleaf/thymeleaf
    compile group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.5.RELEASE'

	
    // https://mvnrepository.com/artifact/org.thymeleaf/thymeleaf-spring4
    compile group: 'org.thymeleaf', name: 'thymeleaf-spring4', version: '3.0.5.RELEASE'


    // https://mvnrepository.com/artifact/nz.net.ultraq.thymeleaf/thymeleaf-layout-dialect
    compile group: 'nz.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version: '2.2.1'
```

And here is my template engine definition.

```
@Bean(name = "templateEngine")
    public TemplateEngine templateEngine() {
        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.setEnableSpringELCompiler(true);
        templateEngine.setMessageSource(messageSource());
        templateEngine.setTemplateResolver(templateResolver());
        LayoutDialect ld = new LayoutDialect();//here it gives exception
        //templateEngine.addDialect(new DataAttributeDialect());
        
        return templateEngine;
    }
```
In debugger, as soon as i hit the line with `new LayoutDialect()` i get the exception.

```
16:03:23.175 [localhost-startStop-1] ERROR o.s.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateEngine' defined in at.miles.cfg.WebConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.TemplateEngine]: Factory method 'templateEngine' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.TemplateEngine]: Factory method 'templateEngine' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 23 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at at.miles.cfg.WebConfig.templateEngine(WebConfig.java:108)
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc.CGLIB$templateEngine$5(<generated>)
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc$$FastClassBySpringCGLIB$$bfd1e72.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc.templateEngine(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 24 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.util.Collection
	at org.codehaus.groovy.runtime.dgm$347.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at nz.net.ultraq.thymeleaf.context.extensions.IContextExtensions.apply(IContextExtensions.groovy:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1445)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:897)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod0SpreadSafe(ScriptBytecodeAdapter.java:198)
	at nz.net.ultraq.thymeleaf.LayoutDialect.<clinit>(LayoutDialect.groovy:59)
	... 35 common frames omitted
16:03:23 ERROR Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'templateEngine' defined in at.miles.cfg.WebConfig: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.TemplateEngine]: Factory method 'templateEngine' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107) ~[spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399) [tomcat-embed-core-8.0.23.jar:8.0.23]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.thymeleaf.TemplateEngine]: Factory method 'templateEngine' threw exception; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 23 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
	at at.miles.cfg.WebConfig.templateEngine(WebConfig.java:108) ~[main/:na]
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc.CGLIB$templateEngine$5(<generated>) ~[main/:na]
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc$$FastClassBySpringCGLIB$$bfd1e72.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	at at.miles.cfg.WebConfig$$EnhancerBySpringCGLIB$$376e07cc.templateEngine(<generated>) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Class cannot be cast to java.util.Collection
	at org.codehaus.groovy.runtime.dgm$347.invoke(Unknown Source) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:91) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125) ~[groovy-all-2.3.10.jar:2.3.10]
	at nz.net.ultraq.thymeleaf.context.extensions.IContextExtensions.apply(IContextExtensions.groovy:36) ~[thymeleaf-layout-dialect-2.2.1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_45]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93) ~[groovy-all-2.3.10.jar:2.3.10]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325) ~[groovy-all-2.3.10.jar:2.3.10]
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1445) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:897) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodN(ScriptBytecodeAdapter.java:168) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSafe(ScriptBytecodeAdapter.java:176) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodNSpreadSafe(ScriptBytecodeAdapter.java:183) ~[groovy-all-2.3.10.jar:2.3.10]
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethod0SpreadSafe(ScriptBytecodeAdapter.java:198) ~[groovy-all-2.3.10.jar:2.3.10]
	at nz.net.ultraq.thymeleaf.LayoutDialect.<clinit>(LayoutDialect.groovy:59) ~[thymeleaf-layout-dialect-2.2.1.jar:na]
	... 35 common frames omitted
```

I recall having similar issue when tried to use this Dialect before compatibility was rolled out.

So it there compatibility or not? I followed the instructions on installation also from a clean project but still gives the same error, so I assume it's not my project config.

Please note that project builds OK. It's at runtime, while starting webapp that problem occurs

**Comment by ultraq** [comment]
Hmm, I don't think I've seen this kind of issue before.  Have you only been trying to upgrade to Thymeleaf 3 and Layout Dialect 2 recently?  Version 2 of the layout dialect was made to be compatible with Thymeleaf 3, so any 2.x.x version should work.  Until I can get a chance to look into it, could you possibly try the latest 2.1.x and 2.0.x versions to see if they work for you?  If it's something that's happening in all 2.x versions, then I might need to direct my investigation to those other things you mentioned, like Tomcat 8 or other parts of Spring.

**Comment by AlekseiBorsenko** [comment]
Thank you for a quick reply. I will try other version and give you the feedback. I will also prepare simple example project that features this issue and host it here so you can check it aswell.

**Comment by AlekseiBorsenko** [comment]
Hello. Just mounted example project that demonstrates the issue

 https://github.com/AlekseiBorsenko/Thymeleaf3LayoutDialect2

Please give me an update if you find the reason behind this issue. I really want some features from Thymeleaf 3 like parsing JS files, but I would like to keep using LayoutDialect cuz it wored like a charm up until now.

Please tell me if you need any more info. And thanks in advance!

**Comment by ultraq** [comment]
I cloned your project, and sure enough got the same error when running script like `gradle appRun`.  However, in trying to get the thing to debug by running on Jetty/Tomcat installed on my machine, I came across some configuration problems in the `build.gradle` script, so edited it until I could get an artifact, and then... it worked.  I ran `gradle appRun` over the modified script, and it ran just fine as well!

I followed [the setup instructions for the Gretty plugin](http://akhikhl.github.io/gretty-doc/Getting-started.html) that you've got in the `build.gradle` file, and ended-up with this:

```groovy
apply plugin: 'war'
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'

sourceCompatibility = '1.8'

repositories {
    mavenCentral()
}

gretty {
    debugPort = 8765      // default
    debugSuspend = true 
    servletContainer = 'tomcat8'
    contextPath = "/"
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.10'
    compile group: 'org.springframework', name: 'spring-webmvc', version: '4.3.7.RELEASE'
    compile group: 'org.thymeleaf', name: 'thymeleaf', version: '3.0.0.RELEASE'
    compile group: 'org.thymeleaf', name: 'thymeleaf-spring4', version: '3.0.0.RELEASE'
    compile group: 'nz.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version: '2.1.0'
}
```

The biggest difference seems to be the way in which the gretty plugin is initiated.  In the config above, I've got the "war" plugin, then applied the script from the URL on the gretty getting started guide, whereas the project you created didn't have the "war" plugin, and then tried to apply the plugin from the Gradle plugin repository.

I haven't investigated further to see which part was at fault (the missing "war" plugin or the way the gretty plugin is applied), but could you try make those modifications to your main project and see if that fixes things for you?

**Comment by AlekseiBorsenko** [comment]
Hello!

I'm sorry for this delay in response. As I had some more pressing tasks with the main project this had to be postponed.

Your example works as a charm. Also I have to inform you that WAR plugin has nothing to do with it, because I just changed the line with gretty plugin application to 
```
apply from: 'https://raw.github.com/akhikhl/gretty/master/pluginScripts/gretty.plugin'
```

I will Push the change to my project so you can provide this solution to anybody who runs into this issue!

Great work there! And Thank you!

**Comment by ultraq** [comment]
Awesome, good to hear that everything worked out 👍
