### ISSUE TITLE
Thymeleaf 3.1.0 support

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-layout-dialect#228]
See if there's anything I need to do to make this work with Thymeleaf 3.1.0 now that it's been released 🥳

**Comment by ultraq** [comment]
I only need to update dependencies for testing, but otherwise it looks like no code changes required to work w/ Thymeleaf 3.1.0 👍

**Comment by anchialas** [comment]
Hi there, 
I have encountered an incompatibility in `FragmentProcessor` with Thymeleaf 3.1.2:
```
No such property: fragmentCollection for class: org.thymeleaf.context.WebEngineContext
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
	at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:172)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
	at nz.net.ultraq.thymeleaf.layoutdialect.fragments.FragmentProcessor.doProcess(FragmentProcessor.groovy:65)
```

FragmentProcessor:
```
	@Override
	@SuppressWarnings('AssignmentToStaticFieldFromInstanceMethod')
	protected void doProcess(ITemplateContext context, IProcessableElementTag tag,
		AttributeName attributeName, String attributeValue, IElementTagStructureHandler structureHandler) {

		// Locate the fragment that corresponds to this decorator/include fragment
		def fragments = context.fragmentCollection[attributeValue]
                ...
```
