### ISSUE TITLE
Useage in spring boot project throws ClassNotFoundException nz.net.ultraq.thymeleaf.layoutdialect.LayoutDialect

### ISSUE THREAD

**Issue by sveri** [ultraq/thymeleaf-layout-dialect#240]
I am trying to add thymeleaf dialect layout to a new project and when configuring it, as stated in the docs (https://ultraq.github.io/thymeleaf-layout-dialect/getting-started/) it throws an NPE:

	2024-02-25T17:38:50.309+01:00 ERROR 20500 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

	java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.context.PropertyPlaceholderAutoConfiguration.propertySourcesPlaceholderConfigurer
			at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForBeanMethod(ConfigurationClassBeanDefinitionReader.java:183) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) ~[spring-context-6.1.4.jar:6.1.4] 
			at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:428) ~[spring-context-6.1.4.jar:6.1.4]      
			at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:289) ~[spring-context-6.1.4.jar:6.1.4] 
			at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:349) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118) ~[spring-context-6.1.4.jar:6.1.4]  
			at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:788) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:606) ~[spring-context-6.1.4.jar:6.1.4]
			at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.3.jar:3.2.3]
			at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.3.jar:3.2.3]
			at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.3.jar:3.2.3]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.3.jar:3.2.3]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.3.jar:3.2.3]
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.3.jar:3.2.3]
			at de.sveri.dlist.DlistApplication.main(DlistApplication.java:13) ~[main/:na]
			at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
			at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
			at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:50) ~[spring-boot-devtools-3.2.3.jar:3.2.3]
	Caused by: java.lang.IllegalStateException: Failed to introspect Class [de.sveri.dlist.Config] from ClassLoader [org.springframework.boot.devtools.restart.classloader.RestartClassLoader@5ec05b84]
			at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483) ~[spring-core-6.1.4.jar:6.1.4]
			at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:360) ~[spring-core-6.1.4.jar:6.1.4]
			at org.springframework.util.ReflectionUtils.getUniqueDeclaredMethods(ReflectionUtils.java:417) ~[spring-core-6.1.4.jar:6.1.4]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.lambda$getTypeForFactoryMethod$1(AbstractAutowireCapableBeanFactory.java:750) ~[spring-beans-6.1.4.jar:6.1.4]
			at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getTypeForFactoryMethod(AbstractAutowireCapableBeanFactory.java:749) ~[spring-beans-6.1.4.jar:6.1.4]    
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineTargetType(AbstractAutowireCapableBeanFactory.java:682) ~[spring-beans-6.1.4.jar:6.1.4]        
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:653) ~[spring-beans-6.1.4.jar:6.1.4]
			at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1644) ~[spring-beans-6.1.4.jar:6.1.4]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:562) ~[spring-beans-6.1.4.jar:6.1.4]
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:534) ~[spring-beans-6.1.4.jar:6.1.4]
			at org.springframework.boot.autoconfigure.condition.OnBeanCondition.collectBeanNamesForType(OnBeanCondition.java:247) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:240) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getBeanNamesForType(OnBeanCondition.java:230) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchingBeans(OnBeanCondition.java:183) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.boot.autoconfigure.condition.OnBeanCondition.getMatchOutcome(OnBeanCondition.java:158) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-3.2.3.jar:3.2.3]
			... 20 common frames omitted
	Caused by: java.lang.NoClassDefFoundError: nz/net/ultraq/thymeleaf/layoutdialect/LayoutDialect
			at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
			at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) ~[na:na]
			at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676) ~[na:na]
			at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465) ~[spring-core-6.1.4.jar:6.1.4]
			... 36 common frames omitted
	Caused by: java.lang.ClassNotFoundException: nz.net.ultraq.thymeleaf.layoutdialect.LayoutDialect
			at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
			at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
			at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
			at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
			at java.base/java.lang.Class.forName(Class.java:534) ~[na:na]
			at java.base/java.lang.Class.forName(Class.java:513) ~[na:na]
			at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:121) ~[spring-boot-devtools-3.2.3.jar:3.2.3]
			at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
			... 40 common frames omitted

Unfortunately I cannot find anything using google or in the docs, so any help is appreciated.

This is my build.gradle:

	plugins {
		id 'java'
		id 'org.springframework.boot' version '3.2.3'
		id 'io.spring.dependency-management' version '1.1.4'
		id 'org.graalvm.buildtools.native' version '0.9.28'
	}

	java {
		sourceCompatibility = '21'
	}

	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter-web'
		implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
		implementation 'nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:3.3.0'
		developmentOnly 'org.springframework.boot:spring-boot-devtools'
		runtimeOnly 'org.postgresql:postgresql'
		testImplementation 'org.springframework.boot:spring-boot-starter-test'
	}

And this is my config class:

	package de.sveri.dlist;

	import org.springframework.context.annotation.Bean;
	import org.springframework.context.annotation.Configuration;

	import nz.net.ultraq.thymeleaf.layoutdialect.LayoutDialect;

	@Configuration
	public class Config {

		@Bean
		public LayoutDialect layoutDialect() {
			return new LayoutDialect();
		}

	}

**Comment by ultraq** [comment]
Odd that it can't find the class 🤔  However, I spot that you've got a GraalVM plugin there, are you running this w/ Graal or as a native image by any chance?  Others have reported issues when trying to use a native image (#235, #229) as GraalVM I think still has trouble running dynamic Groovy code.

**Comment by sveri** [comment]
Thank you for looking into this. 
A new day, new idea, so, I just cleaned my whole gradle cache, after restarting everything and suddenly it works. 

It seems like there is a bug in gradle or the VSCode java plugin, however, everything works now. 

Sorry about the confusion, I should have cleaned the cache yesterday already.
